### PR TITLE
gh-193-Commit of Gaffer Docker files

### PR DESCRIPTION
**Pull request by ng12developer**
New pull request for Docker, please ignore pull request 176.

### CODE REVIEW

**Comment by p013570** [comment]
See comments from old pull request gh-176.

**Comment by gaffer01** [comment]
Please remove the file LICENSE from all of the subfolders. Remove all the commented out lines from the file ssh_config (but leave the copyright and Apache license notice).

**Comment by ng12developer** [comment]
LICENSES removed and ssh_config edited.

**Comment by p013570** [comment]
In the last release of Gaffer there were a few modifications that mean unfortunately some changes need to be made to the docker scripts to get them working again with Gaffer 0.3.5.

- Java version now needs updating in the base docker script to 1.8.
- The gaffer examples have been refactored, so gaffer/setup_files/configure_store_prop.sh will need to be updated to use the correct path for the store properties.
- The test at the end of the guide will need to be updated to use the slightly modified film example.

Also, we could do with 'yum install -y tar' being added to the top of Dockerfile.centos6.gaffer and Dockerfile.hadoop.centos6.

**Comment by ng12developer** [comment]
I will adapt the examples to get in line with 0.3.5.

Can I clarify that its is Java 1.8 that is needed on the base image? The Gaffer code base for 0.3.5 and the develop branch still reference 1.7 and the Gaffer image will inherit from the base. There is also an issue of not having tested the Hadoop version is fully compatible with 1.8, whose image also inherits from the base.

**Comment by p013570** [comment]
Brilliant, thanks. 

The core framework of Gaffer still requires Java 1.7, however the TinkerPop implementation that was added as a module in 0.3.5 requires 1.8. So in order to build the entire project Java 1.8 is required. If the hadoop testing is a problem, for the time being you could leave Java at 1.7 and exclude the tinkerpop module from the maven build. If using maven with version > 3.2.1 then you can use:
```bash
mvn clean install -pl \!tinkerpop
```

**Comment by ng12developer** [comment]
Adapted examples for version 0.3.5.
tinkerpop module excluded from maven build of master code base.
tar commands added.

**Pull request closed without merging**
