### PR TITLE
gh-57 - added result limit to get operations

### PR DESCRIPTION
**Pull request by p013570**

### CODE REVIEW

**Comment by GCHQ-11** [comment]
Could this result limit functionality be implemented as a separate operation?
OperationChain.first(GetElements).then(LimitElements)

Where Limit elements took INPUT -> Iterable<SOMETHING>, OUTPUT -> Iterable<SOMETHING>

**Comment by p013570** [comment]
Closing pull request whilst we make the suggested changes

**Comment by GCHQ-11** [comment]
Now that we have the Limit as a separate step, do we still need the limit parameter in the AbstractGetOperation (together with the need to add a function to all the child class builders)

**Comment by p013570** [comment]
I think the limit parameter is actually quite useful. It makes it a lot simpler and avoids users having to provide 2 operations when they need to limit their results. It also follows the same pattern we did for deduplicating results.

**Pull request merged**
