### PR TITLE
Initial Commit for Gaffer Docker

### PR DESCRIPTION
**Pull request by ng10developer**
Initial Gaffer Docker files with documentation

### CODE REVIEW

**Comment by ng10developer** [comment]
Ready for Review

**Comment by ng10developer** [comment]
Require merge once reviewed

**Comment by gaffer01** [comment]
In "Building-and-Deploying-Gaffer-Container", there is an issue on step 8:

```docker build --rm -t gaffer-docker/centos6:base -f Dockerfile.centos6 .```

This fails with `Error: image gaffer-docker/centos6 not found`. Changing the FROM line in Dockerfile.centos6 to `centos:centos6.7` fixes this problem.

**Comment by p013570** [comment]
Please have a quick look at our branching strategy: https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/wiki/Ways-of-Working#git-branching-model

Issues should be worked off the develop branch and merged back into the develop branch.

**Comment by ng10developer** [comment]
There is a missing step in the instructions, where you pull the centos:centos6.7 image from docker git hub and then use the docker tag command to tag the centos:centos6.7  with the name gaffer-docker/centos6:centos6.7
However it probably aids usability to eliminate this step as you suggest and  just pull the cents:centos6.7 image directly

**Comment by ng10developer** [comment]
see pull request 171

**Comment by ng10developer** [comment]
See pull request 171

**Comment by p013570** [comment]
Closed pull request as the work will be merged in via pull request gh-171.

**Pull request closed without merging**
